### ISSUE TITLE
support k3s and k0s runtime

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#1092]

**Comment by fanux** [comment]
sealos run k8s 

sealos run k0s

sealos run k3s

FROM k8s
CMD xxxx

FROM k3s
CMD helm install xxx

**Comment by fanux** [comment]
https://github.com/labring/sealos/blob/main/pkg/runtime/runtime.go

**Comment by allencloud** [comment]
> sealos run k8s
> 
> sealos run k0s
> 
> sealos run k3s
> 
> FROM k8s CMD xxxx
> 
> FROM k3s CMD helm install xxx

@fanux @cuisongliu 
Is it more proper to support this in sealer? After all, sealer could be some kind of upstream. And sealer community is doing this now. It would be duplicated waste of work of two groups. Anyway, I found that pkg/runtime almost takes all code from sealer repo.

**Comment by fanux** [comment]
@allencloud I think it is better to use the sealer runtime, but the ability needs to be checked, the interface is not the same at present, and a unified interface needs to be developed.  sealos did fork the code of sealer and made some modifications, as explained in the readme. This is a short-term solution, the long-term solution standards must be unified, and the interface must be unified in order to form some reusable libraries.

**Comment by fanux** [comment]
We temporarily close this issue and other sealer runtimes to implement these functions and call them directly.
Before this, we need to define the runtime interface together. @allencloud

**Comment by fanux** [comment]
@allencloud
1. Added IPVS logic to runtime interface
2. Token implementation logic
3. kubeadm configuration logic
4. The registry logic only retains http
5. image-cri-shim component
6. Remove all exec scripts

Those are the modified content.

**Comment by yhm-amber** [comment]
Dose the k0s or k3s have some Kubefile ?
