### ISSUE TITLE
Feature: Split actions ci `build-images` to concurrent

### ISSUE THREAD

**Issue by zzjin** [labring/sealos#1257]
Split build-images ci workflow to accelerate built speed.

The most time-consuming operation is `build in docker`

1. prepare docker image (prepare build images and do not install packages each time?)
2. prepare goreleaser(same optimization above?)
3. build bin file one by one(add matrix build?)

**Comment by cuisongliu** [comment]
```
FROM --platform=$BUILDPLATFORM golang:1.17-buster as builder
RUN dpkg --add-architecture arm64 &&  \
      apt update &&  \
      apt install -y gcc-aarch64-linux-gnu && \
      apt install -y libbtrfs-dev btrfs-tools && \
      apt install -y libgpgme-dev libdevmapper-dev && \
      apt install -y libbtrfs-dev:arm64 btrfs-tools:arm64 && \
      apt install -y libgpgme-dev:arm64 libdevmapper-dev:arm64 
```


build amd64 and arm64 baseimage

**Comment by zzjin** [comment]
Seems we can split these into arch-spec images?

**Comment by SignorMercurio** [comment]
FYI: https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

**Comment by zzjin** [comment]
so we can prebuild one image and publish to docker hub to speed up images prepare?

**Comment by SignorMercurio** [comment]
About task 1 & 2, after adjusting the workflows it's currently not worthy to use pre-built images in the workflows because doing so would at most decrease the running time by around **10 sec**[1], if not increasing it. Besides, `build in docker` steps in the previous release workflow is no longer needed[2].

As for task 3, it's already done in #1261. Therefore maybe we should close this?

[1] For example, when running golangci-lint, a pre-build image may reduce the time consumed in the red frame below, which can be ignored compared to the long duration of `Run Linter` step.

![image](https://user-images.githubusercontent.com/32540679/178434274-40772b77-f27c-471d-9650-664a0de1b0ee.png)

[2] For more details, check out changes in `.github/workflow/release.yml` in #1296.

**Comment by zzjin** [comment]
Great, Close this issue to to better work of #1265
