### ISSUE TITLE
Feature: sealos apply process optimize

### ISSUE THREAD

**Issue by cuisongliu** [labring/sealos#2380]
### What is the problem this feature will solve?

Optimize the apply module

**Comment by cuisongliu** [comment]
apply idempotent

**Comment by mond77** [comment]
```
func (c *Applier) Apply() error {
	clusterPath := constants.Clusterfile(c.ClusterDesired.Name)
	var err error
	defer func() {
		if len(c.callback) != 0 {
			for _, fn := range c.callback {
				fn()
			}
		}
		logger.Debug("write cluster file to local storage: %s", clusterPath)
		saveerror := yaml.MarshalYamlToFile(clusterPath, c.getWriteBackObjects()...)
		if err == nil {
			err = saveerror
		}
	}()
	c.initStatus()
	if c.ClusterDesired.CreationTimestamp.IsZero() && (c.ClusterCurrent == nil || c.ClusterCurrent.CreationTimestamp.IsZero()) {
		err = c.initCluster()
		c.ClusterDesired.CreationTimestamp = metav1.Now()
	} else {
		err = c.reconcileCluster()
		c.ClusterDesired.CreationTimestamp = c.ClusterCurrent.CreationTimestamp
	}
	c.updateStatus(err)
	return err
}
```
`saveerror := yaml.MarshalYamlToFile(clusterPath, c.getWriteBackObjects()...)`code here writes the DesiredCluster to Clusterfile, I think the problem may be that we do not check the true apply result when errors happen.

`sealos add` is not idempotent, my solution might be check true cluster nodes with DesiredCluster. the check should happen when errors happen.Take 'sealos add' for examples, it should check the true cluster nodes when ScaleProcessor returns error.
So we can take the same way to add the check to all Processors so that the apply can be retry after failure.

**Comment by cuisongliu** [comment]
we need save masters and nodes to status . diff spec and status .

**Comment by mond77** [comment]
> we need save masters and nodes to status . diff spec and status .
> 
> if exec failed not save status .

what if some nodes was added to cluster while other failed to join.
try to scale back or save joined nodes?

**Comment by fengxsong** [comment]
> > we need save masters and nodes to status . diff spec and status .
> > if exec failed not save status .
> 
> what if some nodes was added to cluster while other failed to join. try to scale back or save joined nodes?

It may be better to save only those nodes that have successfully joined. `applydrivers` module needs refactoring.

**Comment by cuisongliu** [comment]
reopen
