### ISSUE TITLE
cluster backup&restore

### ISSUE THREAD

**Issue by kinbod** [labring/sealos#3406]
### What is the problem this feature will solve?

How does sealos backup&restore cluster? Will you provide one or we need solve it self?

### If you have solution，please describe it

wether sealos will integrate some tool to solve backup&restore？？？

**Comment by bxy4543** [comment]
you can back up the etcd data by yourself, and you have restored the etcd data to restore the cluster when the cluster crashes. The persistent data on the cluster needs to be backed up by yourself, because users contain various types of data storage volumes, and we cannot adapt to various storage backups.
